# Generated by Django 2.0.6 on 2018-11-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagelabels',
            old_name='short_name',
            new_name='shortName',
        ),
    ]
